# Generated by Django 4.0.3 on 2022-04-25 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_thru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleapp.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='cats',
            field=models.ManyToManyField(through='simpleapp.ProductCategory', to='simpleapp.category'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product_thru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleapp.product'),
        ),
    ]
