# Generated by Django 4.0.3 on 2022-04-25 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_productcategory_product_cats_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='cat_thru',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='product_thru',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productmaterial',
            old_name='material_thru',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='productmaterial',
            old_name='product_thru',
            new_name='product',
        ),
    ]
